# Generated by Django 3.0.4 on 2020-03-25 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("backend", "0002_add_data")]

    operations = [
        migrations.RenameField(model_name="photo", old_name="url", new_name="src")
    ]
